# Generated by https://github.com/lukasdietrich/proxyproxy

export http_proxy="{{ .scheme }}://{{ .host }}:{{ .port }}"
export https_proxy="{{ .scheme }}://{{ .host }}:{{ .port }}"

export HTTP_PROXY="{{ .scheme }}://{{ .host }}:{{ .port }}"
export HTTPS_PROXY="{{ .scheme }}://{{ .host }}:{{ .port }}"

export no_proxy="localhost,127.0.0.1"
export NO_PROXY="localhost,127.0.0.1"
